### ISSUE TITLE
Ships

### ISSUE THREAD

**Issue by leboldh** [cs361fall2018/project-haley_jonathan_mark_trevor#1]
User Story: As a player in the game, I want to be able to place my ships so I can play Battleship.

Implement:
- Constructor, must accept string of ship kind
stores parameter in a private variable of string
stores list of squares where ship is occupying
kind can be Battleship, Cruiser, or Destroyer
- getOccupiedSquares, no parameters
returns list of type square

Estimated time:
30 minutes

**Comment by leboldh** [comment]
Ship name should be in capitals, i.e. "MINESWEEPER"
Coordinate received indicates top or left square occupied by ship

**Comment by isvpursuit** [comment]
We either need a setter for Occupied Squares or we need the default constructor to automatically generate the correct Occupied Squares

We need a getter for Ship Type

**Comment by leboldh** [comment]
That's a good point on the squares. The getter for ship type is done. Because the coordinates aren't received by either of the constructors (default or no, and the JsonProperty for occupiedSquares is private to Ship so placeShip can't alter it), I'll make a setter that placeShip can call with the coords after verifying they're valid.
