### ISSUE TITLE
Board - placeShip

### ISSUE THREAD

**Issue by leboldh** [cs361fall2018/project-haley_jonathan_mark_trevor#5]
User Stories: 
1. As a player in the game, I want to be able to place my ships so I can play Battleship.
2. As a player, I want to be able to place my ships vertically or horizontally, so that I can be strategic in my placements.

Implement:
placeShip, receives ship, coordinates, and verticality

1. check bounds, make sure int is between 1-10, and char is between A and J
2.  if bounds are not valid, return false

3. create list of squares ship will occupy

4. get list of ships
5. get coordinates (squares) from all ships
6. if list of squares of new ship conflict with any old ships, return false

7. if coordinates of new ship do not conflict and are within bounds, return true

Estimated time:
30 minutes

**Comment by cookema** [comment]
![battleship image](https://user-images.githubusercontent.com/43457817/46699929-2ccbf400-cbd0-11e8-866d-111edacd5005.png)
