### ISSUE TITLE
Implement Captain's Quarter's AGILE style

### ISSUE THREAD

**Issue by isvpursuit** [cs361fall2018/project-haley_jonathan_mark_trevor#55]
Board class changes (minimal)

'attack' command in Board class
Change Validation to allow attacking Captain's Quarters twice if ship not sunk
In the event of a hit
	Ship only takes damage if square hit is Captain's Quarters
	If Captain's Quarters is hit but ship is not sunk
return Miss and decrement life
		do NOT store attack result in list of attacks
	If Captain's Quarters is hit and life == 0, do normal.

Ship class changes
	Add a value that is Captain's Quarters
represents second to last square in OccupiedSquares
need getter for it

**Comment by isvpursuit** [comment]
Implemented and working, only potential design issue is that when a ship is sunk, it is removed from the board and the player is not notified a ship was sunk. Therefor they might sink a ship before hitting all of the spots and then waste turns trying to hit a ship that is sunk.

solution1: add a notification when a ship is sunk

solution 2: when ship is sunk, automatically fill all spaces controlled by that ship with hits before sinking it.

**Comment by cookema** [comment]
Got an issue open for reporting what ship is sunk. Closing this issues.
